[package]
name = "ockam_lease"
version = "0.1.0"
authors = ["Michael Lodder <mike@ockam.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/ockam-network/ockam"
repository = "https://github.com/ockam-network/ockam/tree/develop/implementations/rust/ockam/ockam_lease"
readme = "README.md"
keywords = ["ockam"]
categories = ["cryptography", "no-std"]
description = """
Leases -- metadata for managing secrets
"""
exclude = [
    "DEVELOP.md",
    "LICENSE"
]

[features]
default = ["std"]
std = ["ockam_core/std", "serde/std"]
alloc = ["ockam_core/alloc", "serde/alloc"]
no_std = ["ockam_core/no_std"]

[dependencies]
ockam_core = { version = "0.3", path = "../ockam_core" }
serde = { version = "1.0", default-features = false }

[dev-dependencies]
serde_bare = "0.3"
serde_json = "1.0"
